### PR TITLE
Fix NUnitXML support

### PR DESCRIPTION
**Pull request by brianbunke**
Following up on #63 (see that PR for tips on quickly testing this module branch):

Added NUnitXML support back in, for those (anyone?) using Vester in CI/CD scenarios.

Just kidding, `Invoke-VesterTest`, you're gone after all. It was calling Pester over and over again in small spurts, which was terrible for both screen output and XML output.

So now, the logic flow is basically:

1. `Invoke-Vester`
    1. User chooses Config, Tests, Remediate, NUnitXML (or accepts defaults)
    2. `Get-ChildItem`, if necessary, to build the full `*.Vester.ps1` test array
    3. For each Config file:
        1. Ensure it's valid
        2. `Invoke-Pester` on the Vester template
2. `VesterTemplate.Tests.ps1`
    1. Receive single config, all tests, remediate preference
    2. Loop through each test one by one:
        1. Determine the scope of the test
        2. Grab `$Title`/`$Desired`/`$Actual`/`$Fix` from `*.Vester.ps1` file
        3. Build the list of relevant VMware inventory objects to test against
        4. Run the test against each object found

Let me know if you find any problems. At this point, I think existing tests just need to be ported to the new format, and we're ready to discuss publishing to the gallery. If you want to help porting tests, please feel free!

### CODE REVIEW

**Comment by equelin** [comment]
Just tested it but it does not seem to work. Everythink works fine except that it does not create any xml file in the path I provided

My workflow:

1. Run New-VesterConfig -Quiet
i. it create correctly the config file

2. Run Invoke-Vester -XMLOutputPath .\vester.xml
i. Tests run as usual
ii. no creation of the vester.xml file

Am I missing something ?

**Comment by chriswahl** [comment]
I found the bug ... the param is defined as `$XMLOutputPath` but the variable used everywhere else is `$XMLOutputFile`.

**Comment by equelin** [comment]
👍  
btw $XMLOutputFile sounds more accurate as we are expected to provide a file...

**Comment by brianbunke** [comment]
I'm dumb. I started with Path and then reached @equelin's conclusion that File seems better. Will fix shortly.

**Comment by chriswahl** [comment]
:shipit:

**Pull request merged**
