### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chriswahl**
Here's where I've started working on all of the changes needed to the `README` to support the new code.

### CODE REVIEW

**Comment by chriswahl** [comment]
Pinging @cars @brianbunke ... I've added the defaults to the `README` in here but I know I missed a few other pieces (such as more examples with tags and perhaps an example without any params at all).

**Comment by brianbunke** [comment]
Changes look good. I can supplement later today.

**Comment by brianbunke** [comment]
Didn't even see the video! Well done, sir

**Comment by chriswahl** [comment]
I realized that as we scope out to meet more environments, a short little "what the heck is this thing" video is probably a good idea. Thanks!

**Pull request merged**
