### PR TITLE
Reorganize project for documentation via gitbook

### PR DESCRIPTION
**Pull request by michaeltlombardi**
+ Replaced all restructured text files with markdown files, transitioning the markup between them to keep the content equivalent.
+ Added scaffolding, including project build script and accompanying psake tasks, for managing project documentation via gitbook.
+ Updated `.gitignore` for the new file types and output.
+ Removed extraneous image and media folder not currently in use.
+ Tasks for documentation auto-generate reference docs for functions and tests based on the captured information from those files.

Related Issues: #70, #104

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
You can find a live preview of the generated docs here:

https://michaeltlombardi.github.io/Vester/

**Comment by michaeltlombardi** [comment]
Second commit fixed some problems I missed with the change log, those should be resolved now.

**Comment by michaeltlombardi** [comment]
Awesome! Let me know what, if any, issues you run into.

A good follow-up issue to this would be a concept doc around the build file.

Loosely, the psake tasks define a way for the executor to install the needed powershell modules, install chocolatey, use chocolatey to install software, and install npm packages - that covers the software prereqs we can't assume will be on every machine.

The project-specific tasks are more around the `compile` task which scaffolds out all the required docs files, including reference docs for the tests. Some of that code could probably be re-used for #157 or could leverage `Get-VesterTest` instead of doing it the way it's implemented here.

**Comment by brianbunke** [comment]
The basics, outputting `.md` files into a new `generate_docs` directory during a build process (e.g. Appveyor):

```posh
# This will install PS modules, gather environment info, and then call psake.ps1
  # If you run this locally, Posh needs admin rights for Chocolatey/NodeJS/etc. installs
.\build.ps1 -TaskList Compile
```

The whole nine yards for any interested parties to investigate on their own; creates a PDF (lol awesome) in the project root, and also serves up the site at `http://localhost:4000` for super sweet local preview action:

```posh
.\build.ps1 -TaskList Compile,GenerateSite,GeneratePdf,LivePreview
```

**Comment by brianbunke** [comment]
Let it be known that on Tuesday, June 20th, 2017, technology won the day.

There will be more battles on the road ahead, and you may grow weary yet. But for tonight, we will revel in our victory, and reflect on the sacrifices of others so that we may fully appreciate this achievement.

**Pull request merged**
