### PR TITLE
Module Overhaul

### PR DESCRIPTION
**Pull request by brianbunke**
1. `Import-Module Vester`
2. `Connect-VIServer vcsa.contoso.com`
3. `New-VesterConfig` _or_ `New-VesterConfig -Quiet`
4. `Invoke-Vester`

Checking this in to get everyone up to speed on where I'm at (and to see if anyone completely hates this plan).

I've decided to overhaul the test structure. In theory, this grants a few benefits:

- Easier to contribute new tests
- Easier to review/maintain tests
- Much more dynamic population of scope, name, etc. for a more uniform presentation
- Eventually (not yet), I hope that `New-VesterConfig` will dynamically know what values need to be populated (and how to populate them) based on the contents of all test files

Still catching up on backfilling the tests. All Hosts tests should be there (except for NFS), and one of each other scope is included as an example.

Test files no longer resemble a Pester test. I'm renaming everything as *.Vester.ps1 because it's a super lazy way to Get-ChildItem, and I can't think of an argument against.

### CODE REVIEW

**Comment by chriswahl** [comment]
@brianbunke I'm getting an error importing the module. 

`Import-Module : The specified module 'Vester' was not loaded because no valid module file was found in any module directory.`

**Comment by brianbunke** [comment]
I think you're probably running into the annoying problem of having the "Vester" parent folder just containing Git scaffolding (readme.md, etc.) and other tests. Currently, I ignore this by importing the child Vester folder directly, which finds the .psd1 file. I hope to publish just the child folder to the gallery, so this problem disappears, and the parent crap stays only with GitHub and runs stuff like Appveyor/Pester CI to validate code changes.

Can you try this from the shell?

    cd $env:USERPROFILE\Desktop
    git clone https://github.com/brianbunke/Vester.git -b module
    Import-Module .\Vester\Vester

**Comment by brianbunke** [comment]
Agreed on the JSON crap, but I haven't brainstormed a better idea to dump a nested hashtable structure that I automatically create (`New-VesterConfig`) into a file for later importing. I am more than happy to consider other solutions, but I thought `New-VesterConfig` was a cool feature request.

Also of note, to help interested parties catch up to my logic. Right now, the chain goes like this:

1. `Invoke-Vester`
2. For each config and each test, `Invoke-Vester` calls `Invoke-VesterTest` repeatedly
  1. I did this because I had issues being locked into just the parameters `Invoke-Pester` accepts, the structure a Pester test file dictates, and I wanted the test files to be far easier to author, edit, and pull dynamic info from (again, for greatly improved `New-VesterConfig` maintenance in the future)
3. (Not current, but in the middle of implementing now:)
  1. `Invoke-VesterTest` calls `Invoke-Pester`
  2. This step is coming back because I realized `2.` just neutered the ability for those who want NUnitXML (and any other Pester features) output, and that kinda sucks
4. `Invoke-VesterTest` / `Invoke-Pester` then runs a template that contains the variables dropped in from the actual test file

In my mind, my next steps are ensuring NUnitXML output isn't completely wiped from the feature list, and populating all tests in the new format. At that point, publishing 1.0.0 is on the table in my mind. I have other ideas, but they could be implemented later.

As always, if you have ideas, I'm open. Just wanted to get this stuff out of my head and committed somewhere more productive.

**Comment by chriswahl** [comment]
Your suggestion to import using `.\Vester\Vester` worked. Thanks!

Ran through the sample four steps that you outlined. Everything worked great for me. I LOVE the new configuration creation function ... tried it verbose at first, and then using `-Quiet`. Very groovy and often asked for feature!

**Comment by chriswahl** [comment]
I'd say :shipit: for now and build from there. This seems demo-able as-is and I like the direction.

**Comment by mattallford** [comment]
My talk tomorrow at vForumAU on the Vester module is going to be out of date, isn't it :) I guess that gives me another small talking point in the value of community and the continuous movement of IT in general.

**Comment by brianbunke** [comment]
@mattallford lol, at the very last second too. Sorry man! (but not sorry...but really actually sorry because I bet that prep was a lot of work)

**Comment by mattallford** [comment]
Haha it was a bit of prep, but all good @brianbunke, the improvements and the effort you have put in have been well worth it! I'll have a play with these latest changes in the lab at some stage and provide some feedback as well mate.

**Comment by equelin** [comment]
@brianbunke I've just reviewed what you have done and it works like a charm 👍  ! (except one little bug for remediating CDROM connections...). 

I really like how you refactored the tests. The syntax you use looks really close to DSL (like Pester tests or PSDeploy files). It's something we could look for in a futur release !?

Like @chriswahl, I'm not sure that JSON is the best data format we could use. I don't like manually editing those files. YAML seem's to be a very good alternatives! It's not natively usable in Powershell but there's some descent implementations available on Internet... 

Except those little subject that can be handle later, I really love what you have done and I think that Vester has a bright futur ;-)

**Comment by chriswahl** [comment]
Have it write a JSON, YAML, and PS1 file :)

**Comment by equelin** [comment]
Yeah sure, why not :-)

btw, data formats seems to be a neverending story !

**Comment by chriswahl** [comment]
To avoid blocking progress, I think JSON is fine (and here are some (http://wahlnetwork.com/2016/02/18/using-powershell-arrays-and-hashtables-with-json-formatting/)[tips] on writing the arrays and hashtables).

It seems like parsing a config file is something that can be pivoted to one or more other formats in the future if refactoring is required.

**Comment by brianbunke** [comment]
You guys are the coolest. @chriswahl @mattallford @equelin ❤️

**Pull request merged**
