### PR TITLE
Additional unit tests

### PR DESCRIPTION
**Pull request by haberstrohr**

### CODE REVIEW

**Comment by brianbunke** [comment]
I'm reworking `.Vester.ps1` requirements as part of overdue work on `New-VesterConfig`. As part of that, @haberstrohr and I will work together on bringing these tests in with the new standards. Leaving this PR sitting around until that point.

**Comment by brianbunke** [comment]
@haberstrohr, it would be super rad if you wouldn't mind updating the tests to add `$Description`/`$Type` as demonstrated in #88.

And, just to call this out so it's easy to search for later: Commit 12a486d of this PR adds `-PassThru` support in `Invoke-Vester`, sending the parameter through for `Invoke-Pester` to handle as usual.

**Comment by haberstrohr** [comment]
Commit 33429e6 and 2af9791 include the updated tests. This new method really does make test writing easier.

**Comment by brianbunke** [comment]
> Removed the unnecessary if/else command from the $actual parameter for applicable tests.

:heart_eyes:

I'll be descending into git merge hell soon to see if we can wipe our hands of this one.

**Comment by chriswahl** [comment]
This is an epic tale of merges. 😄

**Comment by haberstrohr** [comment]
Nothing like adopting changes midstream. 😅

**Pull request merged**
