### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by brianbunke**
Shamelessly stealing Brandon's [PoshBot](https://github.com/poshbotio/PoshBot) template. Anyone, feel free to comment if you'd like to see something different on this template.

We should eventually add `CONTRIBUTING.md` & `PULL_REQUEST_TEMPLATE.md` here as well, but I didn't want to take the time right now to rewrite them for Vester.

### CODE REVIEW

**Comment by Midacts** [comment]
That's a good idea. Github sure does have alot of cool features.
[issue_template.md](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by michaeltlombardi** [comment]
Hooray! This is a great start!

**Comment by brianbunke** [comment]
@chriswahl 

atme

**Comment by chriswahl** [comment]
@brianbunke LOL

**Pull request merged**
