### PR TITLE
Issue# 118 - Sort Config.json

### PR DESCRIPTION
**Pull request by Midacts**
This PR is in reference to #118 
the changes have been tested and verified.

I also changed 3 aliases so they no longer use aliases (where, select, sort)
_<don't hate me for that>_

### CODE REVIEW

**Comment by Midacts** [comment]
Ahh i think it has a merge conflict. It must be because i didn't notice i had those two test tacked onto it  : [
It is possible to remove those two test files? or would it need to be a new PR.

**Comment by brianbunke** [comment]
Sure, you can delete the files from the branch and make another commit.

**Comment by Midacts** [comment]
Awesome. [That](http://stackoverflow.com/questions/9498201/delete-file-from-pull-request-on-github) is good to know.

**Comment by brianbunke** [comment]
:shipit:

**Pull request merged**
