### PR TITLE
Nfs test

### PR DESCRIPTION
**Pull request by cars**
This moves the Get-AdvancedSettings stuff outside of the IT block .. This seems to speed up the tests significantly.....
Cleaned up Describe block....

### CODE REVIEW

**Comment by brianbunke** [comment]
Test performs 3-4x faster in my three-host test lab! Must be killing it in your large environments. :checkered_flag: 

I found the following:

1. Line 38 should be plural: `$hostadvsettings.$setting`
2. Line 35 isn't needed
3. I don't think the ForEach loop at 29 is even needed, with some slight modifications below it

Item 1 breaks the test, and needs a fix. Item 3 can easily be circled back on at a later date, if you don't want to wrestle with it now.

**Comment by cars** [comment]
Ok @brianbunke  I think I've made the changes for #1 and #2 above. I left #3 as is for now....

**Comment by brianbunke** [comment]
Looks good here :+1:

**Comment by cars** [comment]
@chriswahl  do you want to see anything else for this PR?

**Comment by cars** [comment]
@chriswahl understood... I'm in a similar boat....

**Comment by chriswahl** [comment]
Wow, this is incredibly faster than the old code. Really great job @cars!!

:shipit:

**Comment by chriswahl** [comment]
Fixes #21

**Pull request merged**
