### PR TITLE
Introduce Invoke-Vester

### PR DESCRIPTION
**Pull request by brianbunke**
Enough talk, let's look at some code. :neckbeard:

I'm going to walk through Invoke-Vester, because I'd like to know if I'm on the right path, and there are some refactoring decisions to be made.

#### Invoke-Vester

- `11-12` Now supporting -WhatIf (also requires wrappers in each test file)
- `14-18` Like Pester, specify the file(s)/folder(s) to run tests from
  - And allow piping from Get-Item/Get-ChildItem
- `22` Switched Config from [string] > [object] to allow for easier tab completion while entering the path
- `27-35` Tags are here for now, but should be discussed. More on this at the end
- `39-46` We need PowerCLI
  - Super fun trivia time! I didn't put the module in #Requires, because then `Import-Module Vester` auto-imports `VMware.VimAutomation.Core`
    - Which you'd think would be fine...
    - ...but because of all the globally scoped ridiculous that loads,
    - you end up with this.
    - requires
    - Might(?) be able to kill that off by not wildcarding in our .psd1
      - But wildcarding is awesome
    - And so are bullets
- `49` Dot-source the config file
  - Ok, two semi-important points here
    1. I changed the variable within the config file to now just be `$cfg`
      - Because it's really confusing for $Config to import $config
    2. Only accepting one config file at a time right now. This could change later
- `51-53` Check if the variable's there right away, and throw (in the towel) if not
- `55-65` Connect to the vCenter in the config file, unless an open connection already exists
- `69`/`71` Loop through the Process block for each file/folder given
- `72-79` Just send the Invoke-Pester call down the line to each test file

#### Whew. Can I at least do anything cool now?

Nope, sorry. You wasted a lot of time reading this.

```
# Tab completion when typing in your config here!
Invoke-Vester -Config S:\uperSecret\config.ps1
# No hash tables! WhatIf support!
Invoke-Vester -Remediate -WhatIf
# Pipe your test path(s)!
Get-Item .\Tests | Invoke-Vester -Config A:\b\c.ps1
Get-ChildItem \\best\pr\ever\ -Filter '*vm*' -File | Invoke-Vester -Verbose
```

#### Problems we should discuss

In order of increasing [rabbles](https://youtu.be/9gSQg1i_q2g), haha

1. $config > $cfg in every test
  1. Code readability, just helps others get up to speed faster
1. Logic to skip tests that are $null or commented out in the config file
  1. Haven't tackled this yet. Thinking it's just an If block at the front of each test file?
1. Running only the tests you want (#38)
  1. I think we get rid of tags completely. Here's the proposal:
    1. Filter tests into subfolders based on scope
      1. Cluster, Host, VM, etc.
    1. Being able to pipe in `Get-ChildItem` hopefully handles most use cases
    1. Split every test into its own file
      1. Is this crazy? I think it works. I feel like you all might lock me up in a leper colony, though

What say you?

### CODE REVIEW

**Comment by mattallford** [comment]
Hi Brian,

Great work. I haven't had an in-depth look, but a quick play with Invoke-Vester looks promising.

> $config > $cfg in every test
> Code` readability, just helps others get up to speed faster

Not too phased here, but I can see where it would be good to change the variable being used as to not cause confusion. If this stays, we'll need to quickly update the tests to reference $cfg.test.item as well (rather than $config.test.item as they still currently are).

> Logic to skip tests that are $null or commented out in the config file
> Haven't tackled this yet. Thinking it's just an If block at the front of each test file?

Yep, I think this is going to be easiest. Just wrap an if block into the test (and template) to check if the $cfg item that is relevant to the test is populated, and if it is, proceed with the test.

Where this is specified within the test will vary between each test, unless we do proceed with splitting every test into its own file. For example, the SMTP check had an It for:
SMTPPort
SMTPSender
SMTPServer

A user of vester may only want to check for the sender and server, so the test would need an if around each It. Is this what you were thinking?

> I think we get rid of tags completely.

Thinking out loud, what are the downsides to keeping tags in?

>Filter tests into subfolders based on scope

I think this should be done, regardless.

> Split every test into its own file

Technically this works, but will this make it harder for the user to try and filter the tests they are interested in running? It could also introduce a bit of a nightmare for a consistent naming standard. 

With that said, if we went down this route, could we do something similar to the vCheck and prompt the user with a GUI of available tests (maybe by adding another parameter such as -SelectTests), and they can check boxes for the tests they want, then we rename the other tests to .disabled (or something) so it doesn't get called when running Invoke-Vester? No need for piping in get-childitem or tagging. Or instead of a GUI, just collect all tests in a variable, do a foreach and prompt the user if they want to enable or disable the test. It could have a brief description that it pulls from the test file, and telling the user they need to enter data for 'x' item in the $config file.

After re-reading, this might be more suitable for someone who wanted to configure this as a scheduled task within an environment.

Might be rambling on a bit here, or getting a bit ahead of myself, just doing some thinking out loud!

**Comment by tvanholland** [comment]
I've written about 10 new tests and I'm finding that tags become less and less useful the more tests I bring in. If I want to run a single test I'm going to call it out specifically because running a test by tag will run 6 other tests along with it.

I like the idea of running a enable/disable script to choose what tests should be included. I run vCheck as well and I think the process is fairly straight forward.

I agree that naming convention is going to be a nightmare. I ended up renaming all my tests to the following format. Not saying this is the right path forward but it helped me keep it all straight while writing new tests.

Cluster-DRS.tests
Cluster-HA.tests
Hosts-DNS.tests
Network-VDS.tests
VM-AutomaticMAC.tests
VM-SyncTime.tests
VM-ToolsAutoUpgrade.tests

**Comment by brianbunke** [comment]
My gut reaction is that marking tests "disabled" is not the most elegant solution, because we're allowing users to supply different config files at will. If you have two environments, and one has NFS storage, there's a bit of back and forth happening.

A trivial example, maybe, but if you have a lot of environments to manage with varying settings, it could prove cumbersome. Because of that, I lean more toward removing/nulling/commenting values from within each config file that you don't care about testing.

A GUI option to create a config file would be a definite future possibility.

I'm all for standardizing test names, because I love RegEx. ([There are dozens of us! Dozens!](https://youtu.be/lKie-vgUGdI)) I didn't mention it above because I don't have a solid proposal right now.

With scope subfolders and standardized names, everything the user needs to know about filtering tests is in the filename. (And line-by-line in the config file, too.) If we still support tags, I think we'd need to create a `Get-VesterTag` cmdlet to expose the categorization to users.

However, the main argument I can see against splitting everything into its own test file is that we then have to massage the order some tests will run in. In the HA discussion #35, we'd ideally have the main HA test run prior to the sub-tests. vCheck does this by prefixing files and folders with a number; that's one of a few different options available to us.

Ultimately, I *think* the tags discussion comes down to:

1. Tags go
  - We have to split tests into individual files
  - We probably have to discuss a naming standard for test files
  - And discuss/address the ordering problem
2. Tags stay
  - Primarily to filter sub-tests within files
    - Meaning we discuss and lock in hard rules for tagging
  - We have to create something like `Get-VesterTag` to expose them to the user
  - And we discuss standards for when tests should sit in the same file vs. being split up

**Comment by mattallford** [comment]
> Because of that, I lean more toward removing/nulling/commenting values from within each config file that you don't care about testing.

This would imply that there is a 1:1 correlation between an item in a configuration file and a test, and that we would be unable to have multiple tests that use the same configuration item somewhere in the test. I can't think of a good example right now, but is this something we want to lock ourselves in to?


> My gut reaction is that marking tests "disabled" is not the most elegant solution, because we're allowing users to supply different config files at will. If you have two environments, and one has NFS storage, there's a bit of back and forth happening.

True. Unless it became a 1:1 mapping of Vester to a config file, and if a user has multiple environments then they just need to create multiple copies of Vester? Not really elegant either, but it is similar to what I've seen people do with vcheck who have multiple environments to report on.

**Comment by brianbunke** [comment]
It may imply 1:1, true, but my hunch is we wouldn't actually make it behave that way. Three tests could easily be "If" checking the same `$cfg` value(s). I mean, every test should probably require `$cfg.vcenter.vc` and its relevant `$cfg.scope.xxx` in addition to what it's actually looking for.

Really tough to have multiple Vester folders once we flip the switch on it being a legit module. Not impossible, but confusing and discouraged.

**Comment by mattallford** [comment]
> Three tests could easily be "If" checking the same $cfg value(s)

Indeed. So what if the user wanted to only run two out of these three tests? They wouldn't be able to control this by setting the $cfg item to empty, or commenting it out, as it would stop all three tests from running.

**Comment by brianbunke** [comment]
Are there three tests that would all use the same value(s)? We probably need an example.

**Comment by mattallford** [comment]
I'm not sure. I just wanted to call it out as a possible limitation if we plan to use the config file as the source of whether a test is run or not. It may be a non-issue, just doing some 'out loud' thinking.

**Comment by brianbunke** [comment]
Fair enough, appreciate the feedback! Nice to get everything considered now while some refactoring is on the table.

**Comment by equelin** [comment]
There's a lot to read here, hope I've not missed something before responding.

Some thoughts about Invoke-Vester:

- Config file (1/2): Is it really useful to dot source the config file in every tests? I would prefer importing it in Invoke-Pester and pass the $config as a parameter to the tests. It implies to slightly refactor tests, but there are not so many existing for now.
- Config file (2/2): I would really appreciate to have the possibility to specify multiple config files, bonus point if I can do this through the pipeline. 
- Module `VMware.VimAutomation.Core` : Why just not set this module as a requirement in the Invoke-Vester manifest ?
- Tags: I've read a lot of things about tags, nobody seems to have the ideal solution (including me of course...). I think that we have to focus on the usability of Vester. If the users have to deal with Tags (major, minor...), Excluded tags, config files, Testnames and so on, I'm not sure that they will really appreciate Vester...

**Comment by brianbunke** [comment]
I think we're in agreement on everything, I just hadn't bothered yet with the Config items you listed off. Now that I've received feedback on this iteration, I think it's probably ready for me to continue down that road.

> - Module VMware.VimAutomation.Core : Why just not set this module as a requirement in the Invoke-Vester manifest ?

Brian five minutes ago: "Because it gives the same result as my pic above."

_Brian tries it again to make sure, and it works perfectly_

Huh. Well that was easy. Thanks!

**Comment by brianbunke** [comment]
@chriswahl How do you feel about merging #40 and this into the module branch?

**Comment by chriswahl** [comment]
:shipit:

**Comment by chriswahl** [comment]
Catching up from a few weeks abroad. Thoughts:

* I never liked the double use of $config so I'm pleased to see both $config and $cfg. More sanity in the code.
* I like the individual folders for the tests. Cleaner looking and easier to maintain I think. Especially as tests grow.
* I've tweaked the PSD1 file's `FunctionsToExport` because the use of a wildcard breaks PowerShell Gallery and other things. It's better to explicitly call out the functions to export. Learned this the hard way with the Rubrik module (and the default behavior of verb-ModuleManifest cmdlets is to break the wildcard). See [this post](http://wahlnetwork.com/2016/02/10/creating-module-manifest-powershell-gallery-nuget/)
* Copied over my Rubrik module installer to make it easier to load the module for those downloading the code (which I use a lot when testing). It's just sitting in root as a simple script.

**Comment by equelin** [comment]
Thanks for merging this PR. I've worked on a few changes and I want to be sure that nobody is working on that too. Hope to propose a PR this weekend:

- Add support for multiple config files
- Add tests inside the Invoke-Vester function for not running tests when a whole part of the $cfg is empty (like $cfg.host)

**Comment by mattallford** [comment]
Just a quick question. If we have more tests to contribute, should we be doing a PR from the master or module branch? Or both?

**Comment by chriswahl** [comment]
@mattallford I'd say on `master` for now. It accrues a bit more technical debt, but adds to the number of tests we can start porting over once the module is completed.

**Comment by equelin** [comment]
I've done some proposals for enhancing the module in the PR #46

**Pull request merged**
