### PR TITLE
Added Update-SMTP Check

### PR DESCRIPTION
**Pull request by mattallford**
Hi guys,

This is my first time dabbling with both Pester and GitHub, so hopefully I have done things correctly!

I've started small for my first contribution, which is to added a check and remediate (if required) the SMTP sender address, port and server for the vCenter Server.

I've tested this change against vCenter 6.

Any feedback is welcome!

Cheers, Matt.

- Created a new test, Update-SMTP.Tests.ps1. This will check and rediate (if required) the SMTP sender, port and mail server advanced properties for the vCenter Server.
- Line 23 in Config.Tests.ps1 has been modified to accept the additional properties as valid keys.
- Line 24 in Config.Tests.ps1 has been added to verify the key count on the config file
- Lines 26>28 in Config.Tests.ps1 have been added to validate the entry type within the config file.
- Lines 24>26 in Config.ps1 have been added, which are comments for the new config options used by the Update-SMTP function.
- Lines 31>33 in Config.ps1 have been added.

### CODE REVIEW

**Comment by brianbunke** [comment]
Welcome!

Most of this seems fine. The big change for me is something we just talked about in the NFS tests (#21). You should be able to do something like this one time for each host, removing the need for the repeated `Get-AdvancedSetting` in each It block:

    $GetAdvSet = Get-AdvancedSetting -Entity $server -Name @($nfsadvconfig.Keys) -ErrorAction SilentlyContinue

^ That's from the NFS discussion, so you'd need to update the Name array as appropriate. (Maybe it takes '*smtp*' wildcarded?)

Calling Get-AdvancedSetting repeatedly was really killing the test performance, so I think we'd like to wrap those Get- requests in a variable for further manipulation.

**Comment by brianbunke** [comment]
Now that I've said that, it occurs to me that this is testing vCenter, and we're not likely to see a big ForEach that kills performance. So I acknowledge that maybe this doesn't matter at all...but striving for performance is always a good goal.

**Comment by mattallford** [comment]
Hi Brian,

Thanks for the feedback, and you are absolutely right! I've had another look and got my head around the layout of the template, and I've added a single call of Get-AdvancedSetting outside of each It block.

I've run the old code (tagged with smtp2) and the new code (tagged with smtp) and put the results below, and it is almost 3 times quicker, so well worth it!

I've added another commit (hopeully I am doing this right), welcome feedback again!

Cheers, Matt.

PowerCLI C:\> Invoke-Pester C:\Scripts\Vester\ -Tag smtp2
Describing vCenter Configuration: SMTP Settings
 [+] 10.0.0.200 SMTP Sender 318ms
 [+] 10.0.0.200 SMTP Port 248ms
 [+] 10.0.0.200 SMTP Server 211ms
**Tests completed in 779ms**
Passed: 3 Failed: 0 Skipped: 0 Pending: 0

PowerCLI C:\> Invoke-Pester C:\Scripts\Vester\ -Tag smtp
Describing vCenter Configuration: SMTP Settings
 [+] 10.0.0.200 SMTP Sender 236ms
 [+] 10.0.0.200 SMTP Port 12ms
 [+] 10.0.0.200 SMTP Server 16ms
**Tests completed in 265ms**
Passed: 3 Failed: 0 Skipped: 0 Pending: 0

**Comment by brianbunke** [comment]
That change looks great! Test is working here...but I'm a jerk, and noticed something else.

Your ForEach loops through each connected vCenter, except that we have the user specify their vCenter server in the config file. I think it probably needs to reference `$config.vcenter.vc` instead of `$global:DefaultVIServers`, so it doesn't go off and remediate unexpectedly.

Making an additional commit, as you did with the other change, is perfect.

**Comment by mattallford** [comment]
Fair point, that change is made now.

I think I made a small mistake, I did the editing in the master branch of my forked copy instead of within a new branch. I'll have to go back and review the basics of Git again, but hopefully this hasn't caused any issues!

**Comment by mattallford** [comment]
Made another minor change to only retrieve the properties we are interested in testing with the Get-AdvancedSetting cmdlet.

**Comment by brianbunke** [comment]
Looks good to me. :shipit:

**Pull request merged**
