### PR TITLE
Create New-VesterConfig

### PR DESCRIPTION
**Pull request by brianbunke**
First draft at auto-generating a config from existing environment

### CODE REVIEW

**Comment by brianbunke** [comment]
This...was a lot of work. And it's not done. But I wanted to check it in and make sure nobody is vehemently opposed to this feature and the way I'm implementing it.

Of note:

1. Would switch the config file to JSON. Not _necessary_, but was the best answer I came up with.
  1. Obviously, that ^ would dictate more refactoring work on the tests files. But that debt has yet to be paid off in the module branch anyway, so /shrug
  2. JSON has no comments. Now relying on `New-VesterConfig` for context of why each setting is there
2. Ends up being _a lot_ of lines because I don't have a good solution to dynamically pull anything in from the tests files themselves.
3. And because I'm not pulling anything from the tests files automatically, that means this file needs to be updated any time a new test is added.
4. As mentioned toward the beginning of the file, I believe the best way for us to skip tests is by setting individual values to `$null`. Then, by having each test run a `If ($value -ne $null)` check at the beginning, that would skip a test if the user set the value to $null (or deleted the line completely).
5. Per-item reviews within each section, while being a nice feature, are going to blow the stupid line count out of the water.

So. I don't know. I like the way it looks when run, and I think it provides a good end-user experience. But it's a large file that will need manual TLC, because I haven't found many answers for modularizing or dynamic population of the code.

**Comment by brianbunke** [comment]
Merging this because I'm chasing a really cool idea, and want to stamp `New-VesterConfig` as a done deal. You had so much time during the middle of VMworld Europe and a vacation to comment. 😆 :shipit:

**Comment by chriswahl** [comment]
Hah, fair enough. I'm alive, I swear! Merged #62 and will review the module code.

**Comment by brianbunke** [comment]
If you're going to spend time catching up, you should head over to the module branch of my fork. Changed a bunch of crap this week. Goal is to make tests way (way) easier to contribute, and for our stuff (config, config tests, new config generation) to dynamically scale instead of having to manually hit every file.

**Comment by chriswahl** [comment]
Done. I'm getting a lot of red text related to loading help. I'm assuming it's some stupid error on my part.

`PS C:\Dropbox\Code\Vester> Invoke-Vester





Describing Test help for Get-CommandVersion in Vester (1.0.0)
 [+] should not be auto-generated 6.18s
 [-] gets synopsis for Get-CommandVersion 49ms
   Expected: value to not be empty
   251:             $Help.Synopsis | Should Not beNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 251
 [-] gets description for Get-CommandVersion 48ms
   Expected: value to not be empty
   256:             $Help.Description | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 256
 [-] gets example code from Get-CommandVersion 49ms
   Expected: value to not be empty
   261:             ($Help.Examples.Example | Select-Object -First 1).Code | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 261
 [-] gets example help from Get-CommandVersion 52ms
   Expected: value to not be empty
   266:             ($Help.Examples.Example.Remarks | Select-Object -First 1).Text | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 266
   Context Test parameter help for Get-CommandVersion
    [-] gets help for parameter: CommandInfo : in Get-CommandVersion 116ms
      Expected: value to not be empty
      289:                         $parameterHelp.Description.Text | Should Not BeNullOrEmpty
      at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 289
Describing Test help for Get-ParametersDefaultFirst in Vester (1.0.0)
 [+] should not be auto-generated 5.03s
 [-] gets synopsis for Get-ParametersDefaultFirst 74ms
   Expected: value to not be empty
   251:             $Help.Synopsis | Should Not beNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 251
 [-] gets description for Get-ParametersDefaultFirst 101ms
   Expected: value to not be empty
   256:             $Help.Description | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 256
 [-] gets example code from Get-ParametersDefaultFirst 93ms
   Expected: value to not be empty
   261:             ($Help.Examples.Example | Select-Object -First 1).Code | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 261
 [-] gets example help from Get-ParametersDefaultFirst 91ms
   Expected: value to not be empty
   266:             ($Help.Examples.Example.Remarks | Select-Object -First 1).Text | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 266
   Context Test parameter help for Get-ParametersDefaultFirst
    [-] gets help for parameter: Command : in Get-ParametersDefaultFirst 164ms
      Expected: value to not be empty
      289:                         $parameterHelp.Description.Text | Should Not BeNullOrEmpty
      at <ScriptBlock>, C:\Dropbox\Code\Vester\Tests\Help\Module.Help.Tests.ps1: line 289
PS C:\Dropbox\Code\Vester>`

**Comment by equelin** [comment]
@chriswahl Perhaps you should provide the path to the Vester tests ?

@brianbunke I really love you idea!

**Comment by chriswahl** [comment]
@equelin It finds the tests, but first fails to load help for a large quantity of cmdlets. I've tried running it as Admin and using Update-Help without avail. After it fails to update help, it does start running the Vester tests as usual because they are within the folder where I am running the `Invoke-Vester` function.

**Comment by equelin** [comment]
I've got a different error message when I run `Invoke-Vester` without any parameter:

```Powershell
EQUELIN@CHE-44WK-EQN : F:\Code\Powershell\Vester\Vester-module : 03/11/2016 17:04:31 :
> Invoke-Vester
Describing  Configuration: Vester-module
 [-] Error occurred in Describe block 354ms
   CommandNotFoundException: Le terme « . » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
   à <ScriptBlock>, F:\Code\Powershell\Vester\Vester-module\Vester\Private\Invoke-VesterTest.ps1 : ligne 32
   à Describe, C:\Program Files\WindowsPowerShell\Modules\pester\3.4.0\Functions\Describe.ps1 : ligne 100
   à Invoke-VesterTest<Process>, F:\Code\Powershell\Vester\Vester-module\Vester\Private\Invoke-VesterTest.ps1 : ligne 31
   à Invoke-Vester<Process>, F:\Code\Powershell\Vester\Vester-module\Vester\Public\Invoke-Vester.ps1 : ligne 122
   à <ScriptBlock>, <Aucun fichier> : ligne 1
```

But it works quiet well when I provide the path to a test:

```Powershell
EQUELIN@CHE-44WK-EQN : F:\Code\Powershell\Vester\Vester-module\Vester : 03/11/2016 17:03:09 :
> Invoke-Vester -Test .\Tests\Host\DNS-Address.ps1
Describing Host Configuration: DNS-Address.ps1
 [+] Host esx142.test.loc - DNS Servers 4.01s
 [+] Host esx141.test.loc - DNS Servers 1.35s
 [+] Host esx143.test.loc - DNS Servers 1.34s
 [+] Host esx241.test.loc - DNS Servers 1.13s
 [+] Host esx242.test.loc - DNS Servers 1.33s
 [+] Host esx243.test.loc - DNS Servers 1.32s
```

**Comment by brianbunke** [comment]
@chriswahl I'm carelessly ignoring your problem because I'm not testing that file right now during my efforts. (And because it won't be included in the gallery publish.) I will work to get it behaving when we're about ready to ship, though, because that file working means our Help documentation is airtight.

@equelin I just got that new commit sorted out Tuesday night, and am super excited about its potential. But it doesn't Get-ChildItem yet (among many other errors you guys will find right now). I will definitely re-introduce that functionality.

**Comment by brianbunke** [comment]
Man I'm mean, and I didn't even include a ;). Now I feel bad.

**Pull request merged**
